### PR TITLE
remove Transcript logging on image saving

### LINKED ISSUE #5: Transcript logging on every image save
The method `ScriptStarter class>>#startUp` in the `Scripting` package makes this: 

```smalltalk
	IsResuming ifFalse: [ Transcript show: 'ScriptStarter did not execute a given script, since it assumes to be executed after a snapshot and not during startup.'.
		^ self. ].
```

Which means that this class writes the text to Transcript on every normal image save. Moreover, it does not end it with `cr` which makes it even more annoying.

### PR DESCRIPTION
**Pull request by pavel-krivanek**
fixes #5

### CODE REVIEW

**Comment by smarr** [comment]
@theseion you have an opinion? I am happy with this. #5 doesn't mention anything that suggests to me that this would be problematic, but then again, I haven't used this in anger for a while.

**Comment by theseion** [comment]
I think it's fine. I personally never use Transcript (and often when others use it you don't see the output because it's not open...).

**Review by theseion — APPROVED** [review]
LGTM!

**Comment by smarr** [comment]
thanks @theseion @pavel-krivanek!

**Pull request merged**
